# Generated by Django 2.0.2 on 2018-03-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corelation', models.CharField(max_length=10)),
                ('value', models.FloatField(max_length=10)),
            ],
        ),
    ]
