# Generated by Django 2.0.2 on 2018-03-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_currencyvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyvalue',
            old_name='corelation',
            new_name='correlation',
        ),
    ]
