# Generated by Django 2.0.2 on 2018-03-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180302_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyvalue',
            name='correlation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CurrencyСorrelation'),
        ),
    ]
