# Generated by Django 2.0.2 on 2018-03-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180302_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyvalue',
            name='correlation',
        ),
    ]
