# Generated by Django 2.0.2 on 2018-03-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_currencyvalue_correlation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrencyValue',
        ),
    ]
