# Generated by Django 2.0.2 on 2018-03-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_currencyvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyvalue',
            name='correlation',
        ),
        migrations.DeleteModel(
            name='CurrencyValue',
        ),
    ]
