# Generated by Django 2.0.2 on 2018-03-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180302_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyvalue',
            name='date',
        ),
    ]
